/**
 * Export Service - Handles PDF export via browser print functionality
 * Preserves the visual appearance of the web application
 */

export interface ExportOptions {
  title: string;
  filename?: string;
  orientation?: 'portrait' | 'landscape';
}

/**
 * Creates a print-friendly version of the content and triggers print dialog
 */
export const exportToPDF = (
  contentElement: HTMLElement | null,
  options: ExportOptions
): void => {
  if (!contentElement) {
    alert('No content to export');
    return;
  }

  // Create a new window for printing
  const printWindow = window.open('', '_blank', 'width=900,height=700');
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }

  // Get the content HTML
  const content = contentElement.innerHTML;

  // Build the print document
  printWindow.document.write(`
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>${options.title}</title>
      <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
      <script src="https://cdn.tailwindcss.com"></script>
      <script>
        tailwind.config = {
          theme: {
            extend: {
              fontFamily: {
                sans: ['Inter', 'sans-serif'],
                serif: ['Merriweather', 'serif'],
              },
              colors: {
                legal: {
                  50: '#f4f6f8',
                  100: '#eef0f3',
                  200: '#e2e8f0',
                  300: '#cbd5e1',
                  500: '#64748b',
                  800: '#1e293b',
                  900: '#0f172a',
                  950: '#020617',
                },
                saffron: '#FF9933',
                indiaGreen: '#138808',
              }
            }
          }
        }
      </script>
      <style>
        @media print {
          @page {
            size: A4 ${options.orientation || 'portrait'};
            margin: 15mm;
          }

          body {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            color-adjust: exact !important;
          }

          /* Hide buttons and interactive elements */
          button, .no-print, [data-no-print] {
            display: none !important;
          }

          /* Ensure backgrounds print */
          * {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }

          /* Page breaks */
          .page-break {
            page-break-before: always;
          }

          .avoid-break {
            page-break-inside: avoid;
          }

          /* Ensure content fits */
          .print-container {
            max-width: 100% !important;
            padding: 0 !important;
            margin: 0 !important;
          }
        }

        /* Screen styles for preview */
        body {
          font-family: 'Inter', sans-serif;
          background: #f4f6f8;
          padding: 20px;
          margin: 0;
        }

        .print-container {
          background: white;
          max-width: 210mm;
          margin: 0 auto;
          padding: 20px;
          box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        .print-header {
          text-align: center;
          border-bottom: 2px solid #FF9933;
          padding-bottom: 15px;
          margin-bottom: 20px;
        }

        .print-header h1 {
          font-family: 'Merriweather', serif;
          color: #0f172a;
          font-size: 24px;
          margin: 0 0 5px 0;
        }

        .print-header .subtitle {
          color: #64748b;
          font-size: 12px;
        }

        .print-footer {
          margin-top: 30px;
          padding-top: 15px;
          border-top: 1px solid #e2e8f0;
          text-align: center;
          font-size: 10px;
          color: #64748b;
        }

        /* Hide scrollbars in print content */
        .overflow-y-auto, .overflow-x-auto {
          overflow: visible !important;
          max-height: none !important;
        }
      </style>
    </head>
    <body>
      <div class="print-container">
        <div class="print-header">
          <h1>${options.title}</h1>
          <div class="subtitle">Generated by NyayaSutra AI Legal Bench • ${new Date().toLocaleDateString('en-IN', {
            day: 'numeric',
            month: 'long',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
          })}</div>
        </div>

        <div class="print-content">
          ${content}
        </div>

        <div class="print-footer">
          <p>This document was generated by NyayaSutra - AI Legal Bench</p>
          <p>For legal research and educational purposes only</p>
        </div>
      </div>

      <script>
        // Wait for Tailwind to process, then print
        setTimeout(() => {
          window.print();
        }, 1000);

        // Close window after print (or cancel)
        window.onafterprint = () => {
          window.close();
        };
      </script>
    </body>
    </html>
  `);

  printWindow.document.close();
};

/**
 * Export case details to PDF
 */
export const exportCaseToPDF = (
  caseTitle: string,
  contentElement: HTMLElement | null
): void => {
  exportToPDF(contentElement, {
    title: `Case Brief: ${caseTitle}`,
    orientation: 'portrait'
  });
};

/**
 * Export hearing transcript to PDF
 */
export const exportHearingToPDF = (
  sessionName: string,
  contentElement: HTMLElement | null
): void => {
  exportToPDF(contentElement, {
    title: `Hearing Transcript: ${sessionName}`,
    orientation: 'portrait'
  });
};
